name: DevSecOps Auto-Remediation Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  security-audit-and-fix:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Build Scanner Container
      run: docker build -t compliance-scanner .

    - name: 1. Run Audit and Generate Report
      run: docker run --rm compliance-scanner python main.py

    - name: 2. Run Auto-Remediation
      run: docker run --rm compliance-scanner python remediate.py > remediation_log.txt

    - name: 3. Save Reports as Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: compliance-results
        path: |
          compliance_report.json
          remediation_log.txt